/*
 * Flickr Uploadr
 *
 * Copyright (c) 2007-2009 Yahoo! Inc.  All rights reserved.  This library is
 * free software; you can redistribute it and/or modify it under the terms of
 * the GNU General Public License (GPL), version 2 only.  This library is
 * distributed WITHOUT ANY WARRANTY, whether express or implied. See the GNU
 * GPL for more details (http://www.gnu.org/licenses/gpl.html)
 */

#include "nsISupports.idl"

[scriptable, uuid(038C001D-0575-4411-9E9C-B5535BE068F3)]
interface UploadObserver : nsISupports {
  void onProgress(in long remaining, in short photoId);
  void onResponse(in AString rsp, in short photoId);
};

[scriptable, uuid(0e0d0b74-2c06-11dc-8314-0800200c9a66)]
interface flIGM : nsISupports {
	void init(in AString pwd, in UploadObserver observer);
	AString thumb(in long square, in AString path);
	AString rotate(in long degrees, in AString path);
	AString resize(in long square, in AString path);
	AString keyframe(in long square, in AString path);
	void upload(in short photoId, in AString version, in ACString preLoad, in AString path, in AString destination, in AString boundary);
	void cancel(in boolean bCancel);
};
