/*
 * Flickr Uploadr
 *
 * Copyright (c) 2007 Yahoo! Inc.  All rights reserved.  This library is free
 * software; you can redistribute it and/or modify it under the terms of the
 * GNU General Public License (GPL), version 2 only.  This library is
 * distributed WITHOUT ANY WARRANTY, whether express or implied. See the GNU
 * GPL for more details (http://www.gnu.org/licenses/gpl.html)
 */

#include "nsISupports.idl"

[scriptable, uuid(0e0d0b74-2c06-11dc-8314-0800200c9a66)]
interface flIGM : nsISupports {
	void init(in AString pwd);
	AString thumb(in long square, in AString path);
	AString rotate(in long degrees, in AString path);
	AString resize(in long square, in AString path);
	AString keyframe(in long square, in AString path);
};
