#include "nsISupports.idl"

[scriptable, uuid(0e0d0b74-2c06-11dc-8314-0800200c9a66)]
interface IGM : nsISupports {
	AString thumb(in long square, in AString path);
	AString rotate(in long degrees, in AString path);
	AString resize(in long square, in AString path);
};
